description: Set up Nix and the caches
name: Setup Nix
inputs:
  cachix_unfree_token:
    description: "CACHIX_AUTH_TOKEN for some-unfree"
    required: false
  github_token:
    description: "GITHUB_TOKEN"
    required: false
runs:
  steps:
    - name: Install nix
      uses: cachix/install-nix-action@v20
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ inputs.github_token }}
        install_url: https://releases.nixos.org/nix/nix-2.9.1/install
        nix_path: "nixpkgs=channel:nixpkgs-unstable"
    - name: Show nixpkgs version
      run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
      shell: bash
    - name: Consume read-only cuda-maintainers cachix
      uses: cachix/cachix-action@v12
      with:
        name: cuda-maintainers
    - name: Consume the read-only free cachix
      uses: cachix/cachix-action@v12
      with:
        name: some-unfree
    - name: Setup writeable unfree cachix
      uses: cachix/cachix-action@v12
      with:
        authToken: ${{ inputs.cachix_unfree_token }}
        name: some-unfree
  using: composite
