name: "Build and populate the unfree cache"
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron:  '40 2 * * *'
  workflow_dispatch:
jobs:
  use-cudatoolkit-root:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup nix
      uses: ./.github/actions/setup-nix
      with:
        cachix_unfree_token: ${{ secrets.CACHIX_AUTH_TOKEN_UNFREE }}
    - name: nix build using CUDAToolkit_ROOT
      run: nix build -L .#use-cudatoolkit-root
  use-legacy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup nix
      uses: ./.github/actions/setup-nix
      with:
        cachix_unfree_token: ${{ secrets.CACHIX_AUTH_TOKEN_UNFREE }}
    - name: nix build .#use-legacy
      run: nix build -L .#use-legacy
